appName: user-service
deployment:
  replicas: 1
  image:
    repository: demoniiexe/microservice-user
    tag: latest
    pullPolicy: Always
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 512Mi
service:
  type: ClusterIP
  port: 5001
  targetPort: 5001

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  averageUtilization: 50